// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOlmbtCZH9YXso5-NBlO2cV3-q2KKPaU',
    appId: '1:782697591400:web:517100391651ff8bc441dd',
    messagingSenderId: '782697591400',
    projectId: 'settingwala-470409',
    authDomain: 'settingwala-470409.firebaseapp.com',
    storageBucket: 'settingwala-470409.firebasestorage.app',
    measurementId: 'G-5QQSEQ7TMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdb7EsU3VRwb13cmE70SqcuAafLLZeOck',
    appId: '1:782697591400:android:7a2828a008c54b3ac441dd',
    messagingSenderId: '782697591400',
    projectId: 'settingwala-470409',
    storageBucket: 'settingwala-470409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEqLQC0bdme2tWt5bqxTU-w-Lotqhw7uY',
    appId: '1:782697591400:ios:7f20260243692567c441dd',
    messagingSenderId: '782697591400',
    projectId: 'settingwala-470409',
    storageBucket: 'settingwala-470409.firebasestorage.app',
    iosClientId: '782697591400-cboj088u93kngonvbbedqqfill1ekg0b.apps.googleusercontent.com',
    iosBundleId: 'com.rektech.settingwalaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEqLQC0bdme2tWt5bqxTU-w-Lotqhw7uY',
    appId: '1:782697591400:ios:7f20260243692567c441dd',
    messagingSenderId: '782697591400',
    projectId: 'settingwala-470409',
    storageBucket: 'settingwala-470409.firebasestorage.app',
    iosClientId: '782697591400-cboj088u93kngonvbbedqqfill1ekg0b.apps.googleusercontent.com',
    iosBundleId: 'com.rektech.settingwalaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATOlmbtCZH9YXso5-NBlO2cV3-q2KKPaU',
    appId: '1:782697591400:web:6acd3e1134224d71c441dd',
    messagingSenderId: '782697591400',
    projectId: 'settingwala-470409',
    authDomain: 'settingwala-470409.firebaseapp.com',
    storageBucket: 'settingwala-470409.firebasestorage.app',
    measurementId: 'G-YZ1BNBDFB2',
  );
}
